# version: '3'
services:
  app:
    build: ./server
    container_name: nodejs2
    ports:
      - 3000:3000
    # environment:
    #   PORT: 3000
    #   DB_URI: mongodb://mongo:27017
    #   DB_NAME: MEANStackDB
    restart: always

  angular-app:
    build: ./Angular6
    container_name: angular-app2
    ports:
      - 80:80